// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRyeSOWpDx6gaMj2VX4X3mvzlZQNkZQyo',
    appId: '1:578062935633:web:5a8ceb3d789a25a3dcfa70',
    messagingSenderId: '578062935633',
    projectId: 'final-exam-app-80b73',
    authDomain: 'final-exam-app-80b73.firebaseapp.com',
    storageBucket: 'final-exam-app-80b73.appspot.com',
    measurementId: 'G-TS8TXWEX9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA83AYyf3lAMB3N_mJkIulr8KLQsfPy1ZM',
    appId: '1:578062935633:android:91d0f5ed77c6fae7dcfa70',
    messagingSenderId: '578062935633',
    projectId: 'final-exam-app-80b73',
    storageBucket: 'final-exam-app-80b73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLI2vD9R_7xbmvo5yzIaSTSAie0eV6cRg',
    appId: '1:578062935633:ios:0f9a7a11c39c53dedcfa70',
    messagingSenderId: '578062935633',
    projectId: 'final-exam-app-80b73',
    storageBucket: 'final-exam-app-80b73.appspot.com',
    iosBundleId: 'com.example.finalExamApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRyeSOWpDx6gaMj2VX4X3mvzlZQNkZQyo',
    appId: '1:578062935633:web:24c6a70ff180f792dcfa70',
    messagingSenderId: '578062935633',
    projectId: 'final-exam-app-80b73',
    authDomain: 'final-exam-app-80b73.firebaseapp.com',
    storageBucket: 'final-exam-app-80b73.appspot.com',
    measurementId: 'G-WS52YMDFL4',
  );
}
